export const ADD_TO_MATCH = 'ADD_TO_MATCH';
export const FETCH_PERSONS = 'FETCH_PERSONS';
export const FETCH_PERSONS_FAIL = 'FETCH_PERSONS_FAIL';
export const FETCH_PERSONS_SUCCESS = 'FETCH_PERSONS_SUCCESS';
export const FETCH_SINGLE_PERSON = 'FETCH_SINGLE_PERSON';
export const FETCH_SINGLE_PERSON_FAIL = 'FETCH_SINGLE_PERSON_FAIL';
export const FETCH_SINGLE_PERSON_SUCCESS = 'FETCH_SINGLE_PERSON_SUCCESS';
export const REMOVE_FROM_MATCH = 'REMOVE_FROM_MATCH';